POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "ansarzk4@gmail.com",
    "password": "qwerty"
}

###

GET http://localhost:3000/invoice HTTP/1.1

###

POST http://localhost:3000/applyCoupon HTTP/1.1
content-type: application/json

{
    "code": "HOSO777"
}

###

POST http://localhost:3000/admin/loginacc HTTP/1.1
content-type: application/json

{
    "email": "ansarzk4@gmail.com",
    "password": "paris"
}

###

